name: checking if ansible syantx is correct
on:
  pull_request:
    branches:
      - main
   
jobs:
  build:
     runs-on: ubuntu-latest
     
     steps:
        - uses: actions/checkout@v2
        
        - name: Run ansible-lint
          uses: ansible-community/ansible-lint-action@main
