name: test

on: 
  pull_request:
      branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: testing
        run: echo "Hello World!"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: ./servers
        run: |
          npm install express mysql2 bcrypt body-parser jest supertest express-validator

      - name: Test cases
        working-directory: ./servers
        run: |
          npm test healthcheck.test.js